FROM node:9
RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install expect
RUN npm install -g vue-cli
RUN npm install -S vue-carousel
RUN npm install -S vue-resource
RUN npm install -S vue-router
RUN npm install -S vue-awesome
RUN npm install -S vue-infinite-loading
RUN npm install -S vue-slider-component
RUN npm install -S vuetrend
RUN npm install -S vue-input-tag